# Generated by Django 5.2.7 on 2025-12-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_address_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='house_no',
            new_name='landmark',
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='Azad Nagar', max_length=255),
            preserve_default=False,
        ),
    ]
