# Generated by Django 5.2.7 on 2025-12-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cart_options_alter_cart_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
