# Generated by Django 5.2.7 on 2025-12-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('banner_image', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Homepage Banner',
                'verbose_name_plural': 'Homepage Banners',
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desktop_image', models.URLField(max_length=500)),
                ('mobile_image', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Carousel Banner',
                'verbose_name_plural': 'Carousel Banners',
                'db_table': 'carousel',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mrp', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('rating', models.FloatField()),
                ('main_image', models.URLField(blank=True)),
                ('hover_image', models.URLField(blank=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('fabric', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('comfort', models.CharField(blank=True, max_length=100)),
                ('occasion', models.CharField(blank=True, max_length=100)),
                ('slug', models.CharField(blank=True, max_length=150, unique=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('top_picks', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['-created_at'],
            },
        ),
    ]
