# Generated by Django 5.2.7 on 2025-12-03 10:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('banner_image', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desktop_image', models.URLField(max_length=500)),
                ('mobile_image', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'carousel',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mrp', models.IntegerField()),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('discount', models.IntegerField()),
                ('product_images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, default=list, size=None)),
                ('category', models.CharField(max_length=100)),
                ('top_picks', models.BooleanField(default=False)),
                ('slug', models.CharField(blank=True, max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
