# Generated by Django 5.2.7 on 2025-12-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_comfort_product_description_product_fabric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
