# Generated by Django 5.2.7 on 2025-12-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='hover_image',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.URLField(blank=True),
        ),
    ]
