# Generated by Django 5.2.7 on 2025-12-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_image_product_hover_image_product_main_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Homepage Banner', 'verbose_name_plural': 'Homepage Banners'},
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Carousel Banner', 'verbose_name_plural': 'Carousel Banners'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
